baseURL: "https://rstudy2020.netlify.app"
languageCode: ko-KOR
title: R로 하는 기초통계
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
params: 
  author: 박상훈
  thumbnail: /images/POLI301.png
  instructor: 
    name: 박상훈
    email: sp23@email.sc.edu
    url: "https://shpark.netlify.app"
    twitter: pherephobia
    github: pherephobia
    office: 305 Gambrell Hall
  logo:
    url: /images/POLI301.png
    alt: Rstudy2020
  course:
    number: Rstudy 2020
    semester: 2020 가을
    days: "월요일"
    time: "09:00-10:30 PM"
    location: "[Zoom Online](장소)"
    twitter: pherephobia
    dates: "2020년 9월 7일-12월 7일"
    github: "pherephobia/Rstudy2020-basic"
    copyrightYear: "2020"
    contactDetails: >-
      Office hours: [Sign up here.](https://calendly.com/sanghoon)
  university: 
    name: University of South Carolina
    url: "https://www.sc.edu/study/colleges_schools/artsandsciences/political_science/index.php"
  school:
    name: Department of Political Science
    url: "https://www.sc.edu/study/colleges_schools/artsandsciences/political_science/index.php"
  primaryColor: "#73000a"
  secondaryColor: "#CC2E40"
  credits: >-
    이 스터디 사이트의 디자인은 [Andrew Heiss](https://www.andrewheiss.com/)와 [Juan Fernando Tellez](https://juanftellez.com/)의 것을 수정한 것입니다.
  meta:
    twitterSite: "@pherephobia"
    twitterCreator: "@pherephobia"
    fbAuthor: ""
