---
title: 학습목표
slug: reference
output:
  blogdown::html_page:
    template: ../pandoc/toc-title_html.template
    toc: true
---



# 스터디 중반(선형회귀모델 이전)이 되면...

- ...`ggplot()`을 이용해 가장 자주 사용되는 다섯 가지 종류의 플롯을 그릴 수 있게 될 것입니다.
- ...`faceet_wrap`을 언제, 어떻게 사용해야하는지 알게 될 것입니다.
- ...`color`를 커스터마이징 할 수 있을 것입니다.
- ...효과적으로 `theme_()` 함수를 사용할 수 있을 것입니다.
- ...`filter`를 이용하여 데이터셋에서 서브셋을 추출할 수 있게 될 것입니다.
- ...논리형 연산자들(`==`, `!=`, `&`, `|`)을 효과적으로 사용하게 될 것입니다.
- ...`summarize` 함수를 이용하여 요약 통계치들(mean, median, min, max)을 계산할 수 있을 것입니다.
- ...`group_by()` 함수를 이용하여 하나 이상의 변수들 간의 관계를 요약 통계치들로 보여줄 수 있을 것입니다.
- ...`group_by()` 함수를 이용하여 집단의 *비율*을 계산할 수 있게 될 것입니다
- ...`mutate` 함수를 이용해 기존의 데이터셋에 새로운 변수를 만들 수 있게 될 것입니다.
- ...`case_when`을 이용해 변수를 새롭게 코딩할 수 있게 될 것입니다.
- ...`arrange` 함수를 이용해 하나 이상의 변수들을 데이터프레임 내에서 정렬할 수 있을 것입니다.
- ...`select` 함수를 이용해 데이터셋에서 특정 변수들만을 선택해 서브셋으로 만들 수 있게될 것입니다.
- ...데이터셋이 서로 다른 키(key)를 가지고 있더라도 `inner_join` 등을 이용하여 두 데이터셋을 하나로 병합(merge)할 수 있게 될 것입니다.
- ...`facotr` 혹은 `factor_reorder`, `parse_factor` 등의 함수를 이용해 분류형 변수를 팩터형으로 변환할 수 있게 될 것입니다.
- ...데이터를 깔끔하게(tidy) 전처리할 수 있게 될 것입니다.
- ...`gather` 함수를 이용해 횡단형 데이터(wide format)를 종단형 데이터(long format)로 변환할 수 있게 될 것입니다.
- ...`geom_smooth`를 이용해 추세선을 그릴 수 있을 것입니다.

# 스터디 후반(선형회귀모델: 단순 & 다중 & 상호작용)이 되면

- ...모집단과 표본의 차이와 왜 우리가 표본으로부터 무언가를 추정하는 것에 대해 신중한지를 이해하게 될 것입니다.
- ...상관계수의 의미를 이해하고 해석할 수 있게 될 것입니다.
- ...통계모델의 용어들을 이해하고 사용할 수 있게 될 것입니다. (예를 들어, 종속변수, 설명변수 등)
- ...`lm` 함수를 이용하여 OLS 모델을 분석하고 그 결과를 산출할 수 있게 될 것입니다.
- ... OLS 모델로부터 얻은 결과를 해석할 수 있게 될 것입니다. (예를 들어, 계수의 결과를 "설명변수의 한 단위 변화가..."와 같은 식으로 해석할 수 있게 될 것입니다)
- ...*연속형 변수*와 *분류형 변수*의 계수 추정치를 해석할 수 있게 될 것입니다.
- ...인과성의 근본적인 문제를 이해하고, 왜 Y에 대한 X의 효과를 추정하기 위해서 단순히 Y에 대해 X를 회귀분석하는 것만으로는 충분하지 않은지를 이해하게 될 것입니다.
- ...신뢰구간이 무엇인지, 그리고 어떻게 해석할 수 있는지를 이해하게 될 것입니다.
- ...영가설을 이용한 가설검정의 논리를 이해하게 될 것입니다.
- ...p-값이 무엇인지, 어떻게 해석하는지, 통계적 유의성이란 무엇인지 이해하게 될 것입니다.
- ...실험연구와 관측연구 간의 차이에 대해 이해하게 될 것입니다.
- ...근본적인 혼재변수(confounds)에 대한 실제 사례들을 설명하고, 특히 이들을 어떻게 다루어야할지에 대해 이야기할 수 있게 될 것입니다.
- ...다중회귀분석의 기본적인 논리에 대해 이해할 수 있게 될 것입니다.
- ...회귀분석 결과표를 어떻게 읽어야할 지 알게될 것입니다 (계수, 표준오차, p-값, 유의성 등)
- ...유의수준의 증감에 따라 1종 오류와 2종 오류 간의 상충관계가 어떻게 나타나는지를 이해하게 될 것입니다.
- ...변수의 측정 단위가 달라졋을 때, 계수 추정치의 결과의 해석이 어떻게 달라지는지 이해하게 될 것입니다.
